version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - proxy-db:/var/lib/mysql
#  proxy:
#    network_mode: host
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ".:/var/www/"
#    working_dir: /var/www/
#    command:
#      - go
#      - run
#      - main.go

volumes:
  proxy-db:
    external: false